{
 "title": "BigStats Dashboard for F5 BIG-IP",
 "description": "Dashboard for the F5 BIG-IP stats exporter, BigStats.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "BigStats_Datasource", "query": "graphite" },
   { "name": "BigStatsDevice", "query": "stats.gauges.device.*" },
   {
    "name": "BigStatsTenant",
    "query": "stats.gauges.device.$BigStatsDevice.tenants.*"
   },
   {
    "name": "BigStatsService",
    "query": "stats.gauges.device.$BigStatsDevice.tenants.$BigStatsTenant.services.*"
   },
   {
    "name": "BigStatsPool",
    "query": "stats.gauges.device.$BigStatsDevice.tenants.$BigStatsTenant.services.$BigStatsService.pool.*"
   },
   {
    "name": "BigStatsSsl",
    "query": "stats.gauges.device.$BigStatsDevice.tenants.$BigStatsTenant.services.$BigStatsService.ssl.*"
   }
  ]
 },
 "panels": [
  { "title": "Device Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BIG-IP Device CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(stats.gauges.device.$BigStatsDevice.global.cpus.cpu*.*), 6, 7)"
    }
   ]
  },
  {
   "title": "BIG-IP Device Memory",
   "type": "graph",
   "description": "BIG-IP Device RAM Usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.device.$BigStatsDevice.global.memory.*, 6)"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Client Side Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.device.$BigStatsDevice.tenants.$BigStatsTenant.services.$BigStatsService.*, 7, 8)"
    }
   ]
  },
  {
   "title": "SSL Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.device.ip-172-31-1-20-us-west-1-compute-internal.tenants.$BigStatsTenant.services.$BigStatsService.ssl.$BigStatsSsl.*, 9, 10)"
    }
   ]
  },
  {
   "title": "Server Pool Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.device.$BigStatsDevice.tenants.$BigStatsTenant.services.$BigStatsService.pool.$BigStatsPool.members.*.*, 11, 12)"
    }
   ]
  }
 ]
}